import {emptyEntry,readStore,saveStore} from './storage';
declare global{interface Window{LEARNING_GLOSSARY:any[];LEARNING_BASE:string;}}
const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s);
let timer:ReturnType<typeof setTimeout>;
export function toast(message:string){const el=$('#toast')!;el.textContent=message;el.hidden=false;clearTimeout(timer);timer=setTimeout(()=>el.hidden=true,4000);}
const termDialog=$<HTMLDialogElement>('#term-dialog')!;
let trigger:HTMLElement|null=null,termId='';
function positionTerm(){if(!termDialog.open||!trigger)return;if(matchMedia('(max-width: 640px)').matches){termDialog.style.removeProperty('left');termDialog.style.removeProperty('top');return;}const r=trigger.getBoundingClientRect(),w=termDialog.offsetWidth,h=termDialog.offsetHeight;const top=r.bottom+10+h<innerHeight?r.bottom+10:Math.max(12,r.top-h-10);termDialog.style.left=Math.max(12,Math.min(innerWidth-w-12,r.left))+'px';termDialog.style.top=Math.min(innerHeight-h-12,top)+'px';}
function showTerm(el:HTMLElement){const t=window.LEARNING_GLOSSARY.find(t=>t.id===el.dataset.term);if(!t)return;trigger=el;termId=t.id;const values={title:t.name,full:t.full,definition:el.dataset.context||t.definition,example:el.dataset.example||t.example,confused:'容易混淆：'+t.confused};for(const [key,value] of Object.entries(values)){$(`[data-term-${key}]`)!.textContent=String(value);}const link=$<HTMLAnchorElement>('[data-term-link]')!;link.href=window.LEARNING_BASE+t.path+(t.anchor?'#'+t.anchor:'');$('[data-term-review]')!.textContent=readStore().records['terms/'+t.id]?.review?'已加入待复习':'加入待复习';termDialog.showModal();positionTerm();}
for(const el of document.querySelectorAll<HTMLElement>('[data-term]'))el.addEventListener('click',e=>{if(e instanceof MouseEvent&&(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey))return;e.preventDefault();showTerm(el);});
termDialog.addEventListener('close',()=>trigger?.focus({preventScroll:true}));
window.addEventListener('resize',positionTerm,{passive:true});
$('[data-term-review]')!.addEventListener('click',()=>{const state=readStore();const id='terms/'+termId;state.records[id]??=emptyEntry();state.records[id].review=true;state.records[id].updated=new Date().toISOString();if(saveStore(state)){$('[data-term-review]')!.textContent='已加入待复习';toast('已加入笔记中的待复习概念');}else toast('保存失败，请导出或复制记录');});
for(const dialog of document.querySelectorAll<HTMLDialogElement>('dialog'))dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))dialog.close();});
const settings=$<HTMLDialogElement>('#settings-dialog')!;$('[data-settings]')?.addEventListener('click',()=>settings.showModal());
const readerNav=$<HTMLDialogElement>('#reader-nav-dialog'),readerNavButton=$<HTMLButtonElement>('[data-reader-menu-open]');
if(readerNav&&readerNavButton){readerNavButton.addEventListener('click',()=>{readerNav.showModal();readerNavButton.setAttribute('aria-expanded','true');const current=readerNav.querySelector<HTMLElement>('[data-menu-current]');const scroll=readerNav.querySelector<HTMLElement>('.reader-menu-scroll');if(current&&scroll){const currentBox=current.getBoundingClientRect(),scrollBox=scroll.getBoundingClientRect();scroll.scrollTop+=currentBox.top-scrollBox.top-(scroll.clientHeight-currentBox.height)/2;current.focus({preventScroll:true});}});readerNav.addEventListener('close',()=>{readerNavButton.setAttribute('aria-expanded','false');readerNavButton.focus({preventScroll:true});});}
const siteNav=$<HTMLDialogElement>('#site-nav-dialog'),siteNavButton=$<HTMLButtonElement>('[data-nav-open]');
if(siteNav&&siteNavButton){siteNavButton.addEventListener('click',()=>{siteNav.showModal();siteNavButton.setAttribute('aria-expanded','true');});siteNav.addEventListener('close',()=>{siteNavButton.setAttribute('aria-expanded','false');siteNavButton.focus({preventScroll:true});});}
const resolveTheme=(t:string)=>t==='auto'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):t;
matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(readStore().settings.theme==='auto')document.documentElement.dataset.theme=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';});
for(const select of document.querySelectorAll<HTMLSelectElement>('[data-pref]')){const pref=select.dataset.pref as 'theme'|'size'|'line';select.value=String(readStore().settings[pref]);select.addEventListener('change',()=>{const state=readStore();if(pref==='theme')state.settings.theme=select.value;else state.settings[pref]=Number(select.value);document.documentElement.dataset.theme=resolveTheme(state.settings.theme);document.documentElement.style.setProperty('--reading-size',state.settings.size+'px');document.documentElement.style.setProperty('--reading-line',String(state.settings.line));if(!saveStore(state))toast('设置保存失败');});}
const page=$<HTMLElement>('[data-record]');if(page){const mobileToc=$<HTMLDetailsElement>('.reader-toc');if(mobileToc&&matchMedia('(max-width:760px)').matches)mobileToc.open=false;const id=page.dataset.record!;const state=readStore();const r=state.records[id]||emptyEntry();const rev=Number(page.dataset.revision||2);if(r.revision!==rev){r.understood=false;r.revision=rev;r.review=true;}state.records[id]=r;state.last=id;if(!saveStore(state))toast('本浏览器无法保存记录，请手动备份笔记。');const persist=()=>{const fresh=readStore();fresh.records[id]=r;fresh.last=id;return saveStore(fresh);};
for(const checkbox of document.querySelectorAll<HTMLInputElement>('[data-record-field]')){const f=checkbox.dataset.recordField as 'read'|'understood'|'lab'|'bookmark'|'review';checkbox.checked=r[f];checkbox.addEventListener('change',()=>{r[f]=checkbox.checked;r.updated=new Date().toISOString();if(!persist())toast('学习状态保存失败');});}
const note=$<HTMLTextAreaElement>('[data-note]');if(note){note.value=r.note;note.addEventListener('input',()=>{r.note=note.value;r.updated=new Date().toISOString();$('[data-save-status]')!.textContent=persist()?'已保存在此浏览器':'保存失败，请复制或导出笔记';});}
const resume=$<HTMLAnchorElement>('[data-resume]');if(r.anchor&&!location.hash&&document.getElementById(r.anchor)&&resume){resume.hidden=false;resume.href='#'+encodeURIComponent(r.anchor);}
const tocLinks=[...document.querySelectorAll<HTMLAnchorElement>('[data-toc-link]')];const sectionLabel=$<HTMLElement>('[data-current-section]');const defaultSection=sectionLabel?.textContent||'文章导读';const targets=tocLinks.map(link=>({link,target:document.getElementById(link.dataset.tocLink!),title:link.dataset.sectionTitle!})).filter(item=>item.target) as {link:HTMLAnchorElement;target:HTMLElement;title:string}[];let active='';let frame=0;
const updateSection=()=>{frame=0;const threshold=Math.min(180,innerHeight*.28);let current:typeof targets[number]|undefined;for(const item of targets)if(item.target.getBoundingClientRect().top<=threshold)current=item;if(!current&&location.hash){const id=decodeURIComponent(location.hash.slice(1));current=targets.find(item=>item.target.id===id);}if(!current){active='';sectionLabel&&(sectionLabel.textContent=defaultSection);tocLinks.forEach(link=>link.removeAttribute('aria-current'));return;}if(active===current.target.id)return;active=current.target.id;sectionLabel&&(sectionLabel.textContent=current.title);tocLinks.forEach(link=>link===current!.link?link.setAttribute('aria-current','location'):link.removeAttribute('aria-current'));if(r.anchor!==active){r.anchor=active;persist();}};
const scheduleSection=()=>{if(!frame)frame=requestAnimationFrame(updateSection);};window.addEventListener('scroll',scheduleSection,{passive:true});window.addEventListener('resize',scheduleSection,{passive:true});window.addEventListener('hashchange',scheduleSection);updateSection();}
const state=readStore(),continueLink=$<HTMLAnchorElement>('[data-continue]');if(continueLink&&state.last?.startsWith('read/')){const target=document.querySelector<HTMLElement>(`[data-course="${state.last}"]`);if(target){continueLink.href=window.LEARNING_BASE+state.last+'/'+(state.records[state.last]?.anchor?'#'+encodeURIComponent(state.records[state.last].anchor):'');$('[data-continue-title]')!.textContent=target.dataset.title!;$('[data-continue-label]')!.textContent='接着上次的问题';$('[data-continue-question]')!.textContent=target.dataset.question||target.dataset.title!;continueLink.textContent='继续阅读 →';}}
for(const node of document.querySelectorAll<HTMLElement>('[data-course]'))if(state.records[node.dataset.course!]?.read)node.classList.add('is-read');
for(const figure of document.querySelectorAll<HTMLElement>('[data-learning-figure]')){const buttons=figure.querySelectorAll<HTMLButtonElement>('[data-figure-step]');buttons.forEach(button=>button.addEventListener('click',()=>{const step=button.dataset.figureStep;buttons.forEach(b=>b.setAttribute('aria-pressed',String(b===button)));figure.querySelectorAll<HTMLElement>('[data-figure-region]').forEach(el=>el.classList.toggle('figure-active',el.dataset.figureRegion===step));figure.querySelectorAll<HTMLElement>('[data-figure-explanation]').forEach(el=>el.classList.toggle('explanation-active',el.dataset.figureExplanation===step));}));}
const imageDialog=$<HTMLDialogElement>('#image-dialog')!;let scale=1;const img=$<HTMLImageElement>('[data-large-image]')!;
for(const a of document.querySelectorAll<HTMLAnchorElement>('[data-zoom]'))a.addEventListener('click',e=>{e.preventDefault();scale=1;img.style.width='100%';img.src=a.href;img.alt=a.dataset.caption||'知识图原图';$('[data-image-caption]')!.textContent=img.alt;$<HTMLAnchorElement>('[data-original]')!.href=a.href;imageDialog.showModal();});
for(const b of document.querySelectorAll<HTMLButtonElement>('[data-image-scale]'))b.addEventListener('click',()=>{scale=Math.max(.5,Math.min(3,scale+(b.dataset.imageScale==='+'?.25:-.25)));img.style.width=scale*100+'%';});
for(const study of document.querySelectorAll<HTMLElement>('[data-slide-study]')){const buttons=study.querySelectorAll<HTMLButtonElement>('[data-slide-step]');buttons.forEach(b=>b.addEventListener('click',()=>{buttons.forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const focus=study.querySelector<HTMLElement>('.slide-focus')!;const box=b.dataset.region?.split(',').map(Number);focus.hidden=!box;if(box){const [left,top,width,height]=box;Object.assign(focus.style,{left:left+'%',top:top+'%',width:width+'%',height:height+'%'});}}));}
for(const pre of document.querySelectorAll('pre')){const b=document.createElement('button');b.className='copy-code';b.textContent='复制';b.type='button';b.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(pre.querySelector('code')?.textContent||'');toast('已复制代码');}catch{toast('复制不可用，请选中代码复制。');}});pre.append(b);}
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();location.href=window.LEARNING_BASE+'search/';}});
