import {useState} from 'react';
import {latency,kvBytes,overlap,batching,cacheBenefit,cachePolicy,cacheTrace,selectDevices,devices} from '../lib/simulations';
const names:Record<string,string>={latency:'把首 token 的时间拆开',kv:'给 KV Cache 算一笔显存账',batch:'观察请求怎样进出批次',cache:'命中之后，加载一定划算吗？',overlap:'让已到达的数据先开始计算',dra:'一次设备分配，逐步发生'};
const predictions:Record<string,string>={latency:'把排队缩短一半，总响应时间也会缩短一半吗？',kv:'上下文翻倍与并发翻倍，哪个更占显存？',batch:'短请求结束后，新请求是否需要等所有请求完成？',cache:'命中率相同，换一种存储介质会改变收益吗？',overlap:'通信已经比计算慢，继续加快计算还会有多少收益？',dra:'显存足够的设备，为什么仍可能不符合请求？'};
function Range({label,value,onChange,min=0,max=100,step=1,unit=''}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number;step?:number;unit?:string}){return <label className="range-label"><span>{label}<strong>{value.toLocaleString()} {unit}</strong></span><input type="range" aria-label={label} value={value} min={min} max={max} step={step} onChange={e=>onChange(Number(e.target.value))}/></label>}
export default function Demo({type}:{type:string}){
 const [a,A]=useState(type==='latency'?800:type==='kv'?8192:type==='cache'?4:type==='overlap'?4:0);
 const [b,B]=useState(type==='latency'?600:type==='kv'?8:type==='cache'?8:type==='overlap'?3:2);
 const [c,C]=useState(type==='latency'?40:type==='kv'?2:type==='cache'?1000:type==='overlap'?5:0);
 const [d,D]=useState(type==='cache'?0:32);const [toggle,T]=useState(true);const [policy,P]=useState<'lru'|'prefix'|'session'>('lru');
 let content;
 if(type==='latency'){
  const r=latency(a,b,50,c,d);content=<><div className="demo-controls"><Range label="队列等待" value={a} onChange={A} max={3000} step={100} unit="ms"/><details className="advanced-controls"><summary>再改变计算与输出条件</summary><Range label="Prefill" value={b} onChange={B} max={2000} step={100} unit="ms"/><Range label="后续每 token" value={c} onChange={C} min={5} max={100} step={5} unit="ms"/><Range label="输出 token 数" value={d} onChange={D} min={1} max={100}/></details></div><div className="timeline" aria-label="请求耗时组成"><span style={{flex:a||1}} className="amber">排队</span><span style={{flex:b||1}} className="violet">Prefill</span><span style={{flex:c*(d-1)||1}} className="teal">Decode</span></div><div className="result-pair" aria-live="polite"><div><small>首 token · TTFT</small><strong>{r.ttft} <em>ms</em></strong></div><div><small>全部输出完成</small><strong>{r.total} <em>ms</em></strong></div></div><p>固定网络等开销 50 ms。总时间 = 排队 + Prefill + 50 + ({d} − 1) × {c}。这是假设每步耗时恒定的教学模型。</p></>;
 }else if(type==='kv'){
  const gb=kvBytes(32,8,128,a,b,c)/2**30;content=<><div className="demo-controls"><Range label="每个序列上下文" value={a} onChange={A} min={1024} max={32768} step={1024} unit="tokens"/><details className="advanced-controls"><summary>调整并发与存储精度</summary><Range label="并发序列" value={b} onChange={B} min={1} max={32}/><Range label="每元素字节" value={c} onChange={C} min={1} max={4}/></details></div><div className="memory-track"><span style={{width:`${Math.min(100,gb/80*100)}%`}}/></div><div className="result-pair" aria-live="polite"><div><small>仅 KV 数据</small><strong>{gb.toFixed(2)} <em>GiB</em></strong></div><div><small>相对 80 GiB 示例预算</small><strong>{(gb/80*100).toFixed(1)}<em>%</em></strong></div></div><p>固定 32 层、8 个 KV heads、head dimension 128。假定所有序列等长；不含权重、激活、分页碎片和量化元数据，超过预算时进度条封顶但结果保留。</p></>;
 }else if(type==='batch'){
 const rows=batching(a,b,toggle);content=<><label className="check"><input type="checkbox" checked={toggle} onChange={e=>T(e.target.checked)}/>连续批处理（关闭后整批结束才补位）</label><Range label="执行到第几步" value={a} onChange={A} max={10}/><Range label="最多同时处理的请求" value={b} onChange={B} min={1} max={3}/><div className="batch-grid">{rows.map(row=><div key={row.time}><b>t{row.time}</b><span>{row.active.map(id=><i key={id} className={`request request-${id}`}>{id}</i>)}</span><small>等待 {row.waiting.join('、')||'无'}</small></div>)}</div><p>A：t0 到达、5 步；B：t0、2 步；C：t1、3 步；D：t3、2 步。每步一 token，忽略 Prefill、KV 和硬件竞争，只观察补位语义。</p></>;
 }else if(type==='cache'){
 const r=cacheBenefit(a,b,c,20);const state=cachePolicy(d%9,policy);content=<><div className="demo-controls"><Range label="需要加载的 KV" value={a} onChange={A} min={1} max={16} unit="GB"/><Range label="有效加载带宽" value={b} onChange={B} min={1} max={64} unit="GB/s"/><Range label="重算时间" value={c} onChange={C} min={100} max={3000} step={100} unit="ms"/></div><div className="result-pair" aria-live="polite"><div><small>加载（含 20 ms 开销）</small><strong>{r.loadMs.toFixed(0)} <em>ms</em></strong></div><div><small>{r.worthwhile?'相对重算节省':'相对重算多花'}</small><strong>{Math.abs(r.savingMs).toFixed(0)} <em>ms</em></strong></div></div><details className="advanced-controls"><summary>继续研究：缓存淘汰策略</summary><label>策略<select value={policy} onChange={e=>P(e.target.value as typeof policy)}><option value="lru">LRU：淘汰最久未访问</option><option value="prefix">前缀优先：优先淘汰 tail</option><option value="session">前缀优先＋会话结束释放</option></select></label><Range label="访问序列位置" value={d%9} onChange={D} max={8}/><p>已访问：{cacheTrace.slice(0,d%9+1).join(' → ')}</p><div className="cache-blocks">{state.cache.map(x=><span key={x}>{x}</span>)}</div><p>命中 {state.hits} 次，未命中 {state.misses} 次。3 个等大块；root/middle/tail 属于同一会话，END 表示结束。简化启发式不是会议 UCM 算法实现，块命中也不等于完整前缀可复用。</p></details></>;
 }else if(type==='overlap'){
 const r=overlap(a,b,c);content=<><div className="demo-controls"><Range label="数据块数" value={a} onChange={A} min={1} max={8}/><Range label="每块通信" value={b} onChange={B} min={1} max={10} unit="ms"/><Range label="每块计算" value={c} onChange={C} min={1} max={10} unit="ms"/></div><div className="pipeline"><div>通信{Array.from({length:a},(_,i)=><span className="violet" key={i} style={{left:`${i*Math.max(b,c)/r.pipelined*100}%`,width:`${b/r.pipelined*100}%`}}>{i+1}</span>)}</div><div>计算{Array.from({length:a},(_,i)=><span className="teal" key={i} style={{left:`${(b+i*Math.max(b,c))/r.pipelined*100}%`,width:`${c/r.pipelined*100}%`}}>{i+1}</span>)}</div></div><div className="result-pair" aria-live="polite"><div><small>串行</small><strong>{r.serial} <em>ms</em></strong></div><div><small>理想流水线</small><strong>{r.pipelined} <em>ms</em></strong></div></div><p>假设通信与计算使用独立资源，块间只有先传后算依赖。现实中的带宽争用、同步和启动成本会减少收益。</p></>;
 }else{
 const required=c===1?96:toggle?48:16;const matching=selectDevices(required,b===2);const chosen=matching[0]?.id;const phases=['库存发布','筛选候选','分配与绑定','节点准备','容器可使用'];content=<><label className="check"><input type="checkbox" checked={toggle} onChange={e=>T(e.target.checked)}/>请求至少 48 GiB（关闭为 16 GiB）</label><label className="check"><input type="checkbox" checked={b===2} onChange={e=>B(e.target.checked?2:1)}/>与 NIC 的 NUMA 0 共置</label><label className="check"><input type="checkbox" checked={c===1} onChange={e=>C(e.target.checked?1:0)}/>模拟容量不足：请求 96 GiB</label><div className="phase-buttons">{phases.map((p,i)=><button key={p} aria-pressed={a===i} onClick={()=>A(i)}>{i+1}. {p}</button>)}</div><div className="device-grid">{devices.map(dev=><div className={a>0&&!matching.some(m=>m.id===dev.id)?'excluded':''} key={dev.id}><b>{dev.id}</b><span>{dev.memory} GiB · NUMA {dev.numa}</span><span>{dev.healthy?'健康':'设备故障'}</span><small>{a===0?'库存属性':matching.some(m=>m.id===dev.id)?a<2?'候选满足条件':dev.id!==chosen?'候选未被选中':a===2?'已分配 '+chosen:a===3?'准备中：尚不能启动':'准备完成':'被条件排除'}</small></div>)}</div><p aria-live="polite">{phases[a]}：{['驱动通过 ResourceSlice 发布设备，库存不是分配结果。','按属性、健康状态和约束筛选；本例有 '+matching.length+' 个候选。',matching.length?'本例选择 '+chosen+'；真实调度还检查 Pod 节点约束与其他资源。':'无候选设备，不能进入分配。',matching.length?'kubelet 调用驱动准备资源，分配完成不代表准备完成。':'尚未分配设备，节点准备不能开始。',matching.length?'驱动准备成功后，容器运行时才能按配置获得设备访问。':'请求仍在等待；没有设备可供容器使用。'][a]}</p><p>这是 DRA 生命周期模型，不执行集群操作；跨驱动拓扑约束依赖实际版本和驱动属性。</p></>;
 }
 return <section className="demo" data-demo={type}><div className="demo-heading"><span className="eyebrow">交互实验</span><h3>{names[type]}</h3></div><details className="prediction"><summary>可选：先预测会发生什么</summary><p>{predictions[type]}</p></details><div>{content}</div><noscript><p>控件需要 JavaScript 才能改变数值；上方默认场景与说明仍可直接阅读。</p></noscript></section>
}
