import {useEffect,useState} from 'react';
import {emptyStore,readStore,saveStore,validateStore,mergeStores,type Store} from '../lib/storage';
function download(name:string,text:string,type:string){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
export default function Notebook({base,titles}:{base:string;titles:Record<string,string>}){
 const [s,S]=useState<Store>(emptyStore);const [incoming,I]=useState<Store|null>(null);const [mode,M]=useState<'newer'|'keep'|'replace'>('newer');const [error,E]=useState('');const [filter,F]=useState('all');
 useEffect(()=>{const refresh=()=>S(readStore());refresh();window.addEventListener('learning-change',refresh);return()=>window.removeEventListener('learning-change',refresh);},[]);
 const entries=Object.entries(s.records).filter(([,r])=>filter==='all'||(filter==='review'?r.review:r.bookmark));
 async function read(file?:File){if(!file)return;if(file.size>5_000_000){E('文件超过 5 MB，请选择学习记录 JSON。');return;}try{I(validateStore(JSON.parse(await file.text())));E('');}catch(e){E((e as Error).message);}}
 function apply(){if(!incoming)return;download('learning-before-import.json',JSON.stringify(s,null,2),'application/json');const merged=mergeStores(s,incoming,mode);if(saveStore(merged)){S(merged);I(null);E('已导入，并下载导入前备份。');}else E('浏览器拒绝保存。记录尚未导入，请保留原文件。');}
 return <><div className="source-note">记录仅存于当前浏览器。换设备或清理浏览器前，请导出备份。</div><div className="notebook-toolbar"><button onClick={()=>download('ai-infra-learning.json',JSON.stringify(s,null,2),'application/json')}>导出全部记录</button><button onClick={()=>download('ai-infra-notes.md',Object.entries(s.records).map(([id,r])=>`## ${titles[id]||id}\n\n${r.note||'尚无笔记'}\n\n已阅读：${r.read}；能解释：${r.understood}；实验完成：${r.lab}\n`).join('\n'),'text/markdown')}>导出 Markdown 笔记</button><label className="button secondary">导入记录<input type="file" accept=".json,application/json" style={{width:'170px'}} onChange={e=>read(e.target.files?.[0])}/></label></div>{error&&<p role="status">{error}</p>}{incoming&&<section className="import-preview"><h2>导入预览</h2><p>文件包含 {Object.keys(incoming.records).length} 条记录，与当前重复 {Object.keys(incoming.records).filter(id=>id in s.records).length} 条。</p><label>重复记录处理<select value={mode} onChange={e=>M(e.target.value as typeof mode)}><option value="newer">保留更新时间较新的记录</option><option value="keep">保留当前记录</option><option value="replace">使用导入记录</option></select></label><button onClick={apply}>备份当前记录并导入</button> <button onClick={()=>I(null)}>取消</button></section>}<label>查看<select value={filter} onChange={e=>F(e.target.value)}><option value="all">全部学习记录</option><option value="review">需要复习</option><option value="bookmark">我的书签</option></select></label>{entries.length?entries.map(([id,r])=><section className="notebook-entry" key={id}><a href={id.startsWith('terms/')?base+'glossary/#'+id.slice(6):base+id+'/'}><h2>{titles[id]||id}</h2></a><div>{r.read&&<span className="tag">已阅读</span>}{r.understood&&<span className="tag">能解释</span>}{r.lab&&<span className="tag">实验完成</span>}{r.review&&<span className="tag">待复习</span>}</div><p>{r.note||'还没有笔记。回到课节，写下你的理解。'}</p><small>{new Date(r.updated).toLocaleString('zh-CN')}</small></section>):<div className="notebook-entry"><h2>从一个问题开始</h2><p>在课节末尾记录理解、书签与实验状态，它们会出现在这里。</p><a href={base+'read/generation/'}>进入第一节 →</a></div>}</>;
}
